version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/google
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/stop_service.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/run_service.sh
      timeout: 300
      runas: root