version: 0.2

phases: 
    build:
        commands:
            - echo "Build block"
            - ls
            - echo "Running tests to check if "Congratulations" present in google file"
            - grep "Congratulations" layout.js
    post_build:
        commands:
            - echo "Post build phase"
artifacts:
    files:
        - scripts/install_dependencies
        - scripts/start_server
        - scripts/stop_server
        - google
        - appspec.yml
    discard-paths: yes
