version: 0.2
phases:
  pre_build:
    commands:
      - cd Signingoogle
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 851725171252.dkr.ecr.us-east-1.amazonaws.com
      - export REPOSITORY_URI=851725171252.dkr.ecr.us-east-1.amazonaws.com/iperk-dev-fcontainer
      - export COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -b -8)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --build-arg BACKEND_API_URL="$BACKEND_API_URL" -t $REPOSITORY_URI:$COMMIT_ID .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$COMMIT_ID
      - echo Writing image definitions file...
      - echo $REPOSITORY_URI:$COMMIT_ID > imagename.txt
artifacts:
    files:
      - 'Signingoogle/imagename.txt'
      - '/scripts/**/*'
      - '/appspec.yml'
